module.exports = {
  type: 'object',
  properties: {
    _id: {
      type: 'string',
      description: 'Autogenerated ID of the user',
      readOnly: true,
    },
    name: {
      type: 'string',
      description: 'Full name of the user',
      example: 'Jane Doe',
    },
    email: {
      type: 'string',
      format: 'email',
      description: 'Email address',
      example: 'janedoe@school.edu',
    },
    password: {
      type: 'string',
      description: 'Hashed password',
      example: '$2a$10$abc...',
      writeOnly: true,
    },
    role: {
      type: 'string',
      enum: ['student', 'staff', 'admin'],
      description: 'User role',
      example: 'student',
    },
    refId: {
      type: 'string',
      description: 'Reference ID to role-specific document',
      example: '60f6e9f2b7a1c142d8ef8c00',
    },
    isActive: {
      type: 'boolean',
      description: 'User active status',
      example: true,
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
      readOnly: true,
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
      readOnly: true,
    },
  },
  required: ['name', 'email', 'password', 'role', 'refId'],
};
