module.exports = {
  type: 'object',
  properties: {
    _id: {
      type: 'string',
      description: 'Autogenerated ID of the user',
      readOnly: true,
    },
    name: {
      type: 'string',
      description: 'Full name of the user',
      example: 'Jane Doe',
    },
    email: {
      type: 'string',
      format: 'email',
      description: 'Email address',
      example: 'janedoe@school.edu',
    },
    password: {
      type: 'string',
      description: 'Hashed password',
      example: '$2a$10$abc...',
      writeOnly: true,
    },
    role: {
      type: 'string',
      enum: ['student', 'staff', 'admin'],
      description: 'User role',
      example: 'student',
    },
    googleId: {
      type: 'string',
      description: 'Google OAuth ID (if authenticated via Google)',
      example: '10987654321',
      nullable: true,
    },
    provider: {
      type: 'string',
      enum: ['local', 'google'],
      description: 'Authentication provider',
      example: 'local',
      default: 'google',
    },
    isActive: {
      type: 'boolean',
      description: 'User active status',
      example: true,
    },
    createdAt: {
      type: 'string',
      format: 'date-time',
      readOnly: true,
    },
    updatedAt: {
      type: 'string',
      format: 'date-time',
      readOnly: true,
    },
  },
  required: ['name', 'email', 'password', 'role'],
};
